

CREATE TABLE employee_salary_audit (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    employee_id NUMBER,
    old_salary NUMBER(10,2),
    new_salary NUMBER(10,2),
    changed_date DATE DEFAULT SYSDATE
);


CREATE OR REPLACE TRIGGER trg_salary_audit
AFTER UPDATE OF salary ON employee
FOR EACH ROW
BEGIN

    INSERT INTO employee_salary_audit (
        employee_id,
        old_salary,
        new_salary,
        changed_date
    )
    VALUES (
        :OLD.employee_id,
        :OLD.salary,
        :NEW.salary,
        SYSDATE
    );

END;
